"""add unified domain model

Revision ID: 8c883911c3d2
Revises: 90ed1f8ea848
Create Date: 2026-08-13 14:31:06.559998
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8c883911c3d2'
down_revision: str | None = '90ed1f8ea848'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IN ('FOOD', 'ELECTRONICS')", name=op.f('ck_brand_brand_category_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand')),
    sa.UniqueConstraint('name', name=op.f('uq_brand_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_brand_slug'))
    )
    op.create_table('warehouse',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('allowed_expiry_days', sa.Integer(), nullable=False),
    sa.Column('default_transfer_moq', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("type IN ('HUB', 'ONLINE', 'OFFLINE', 'BUYOUT')", name=op.f('ck_warehouse_warehouse_type_valid')),
    sa.CheckConstraint('allowed_expiry_days >= 0', name=op.f('ck_warehouse_warehouse_expiry_days_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse')),
    sa.UniqueConstraint('name', name=op.f('uq_warehouse_name'))
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_group', sa.String(length=128), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_channel_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel')),
    sa.UniqueConstraint('name', name=op.f('uq_channel_name'))
    )
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.create_index('ix_channel_channel_group', ['channel_group'], unique=False)
        batch_op.create_index('ix_channel_warehouse_id', ['warehouse_id'], unique=False)

    op.create_table('logistics_cost',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('departure_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('arrival_warehouse_id', sa.Integer(), nullable=False),
    sa.Column('cost_per_tu', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('cost_per_tu >= 0', name=op.f('ck_logistics_cost_logistics_cost_non_negative')),
    sa.CheckConstraint('departure_warehouse_id <> arrival_warehouse_id', name=op.f('ck_logistics_cost_logistics_cost_distinct_endpoints')),
    sa.ForeignKeyConstraint(['arrival_warehouse_id'], ['warehouse.id'], name=op.f('fk_logistics_cost_arrival_warehouse_id_warehouse')),
    sa.ForeignKeyConstraint(['departure_warehouse_id'], ['warehouse.id'], name=op.f('fk_logistics_cost_departure_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logistics_cost')),
    sa.UniqueConstraint('departure_warehouse_id', 'arrival_warehouse_id', name='uq_logistics_route')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('pack_qty_per_tu', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('pack_qty_per_tu > 0', name=op.f('ck_product_product_pack_qty_positive')),
    sa.CheckConstraint('purchase_price >= 0', name=op.f('ck_product_product_price_non_negative')),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_product_brand_id_brand')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product')),
    sa.UniqueConstraint('product_code', name=op.f('uq_product_product_code'))
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('ix_product_brand_id', ['brand_id'], unique=False)

    op.create_table('inbound',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('bl_no', sa.String(length=64), nullable=True),
    sa.Column('purchase_code', sa.String(length=64), nullable=True),
    sa.Column('production_code', sa.String(length=64), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('arrival_warehouse_id', sa.Integer(), nullable=True),
    sa.Column('shipping_date', sa.Date(), nullable=True),
    sa.Column('korea_arrival_date', sa.Date(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('carton_qty', sa.Integer(), nullable=True),
    sa.Column('unit_qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('payment_amount_krw', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('생산국출발', '해상운송중', '한국도착', '통관중', '입고일선정중', '입고완료')", name=op.f('ck_inbound_inbound_status_valid')),
    sa.CheckConstraint('unit_qty >= 0', name=op.f('ck_inbound_inbound_unit_qty_non_negative')),
    sa.ForeignKeyConstraint(['arrival_warehouse_id'], ['warehouse.id'], name=op.f('fk_inbound_arrival_warehouse_id_warehouse')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_inbound_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inbound'))
    )
    with op.batch_alter_table('inbound', schema=None) as batch_op:
        batch_op.create_index('ix_inbound_eta', ['eta'], unique=False)
        batch_op.create_index('ix_inbound_expiry_date', ['expiry_date'], unique=False)
        batch_op.create_index('ix_inbound_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_inbound_status', ['status'], unique=False)

    op.create_table('inventory_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('qty >= 0', name=op.f('ck_inventory_snapshot_inventory_snapshot_qty_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_inventory_snapshot_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_inventory_snapshot_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_snapshot')),
    sa.UniqueConstraint('snapshot_date', 'warehouse_id', 'product_id', 'expiry_date', name='uq_inventory_snapshot_lot')
    )
    with op.batch_alter_table('inventory_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_inventory_snapshot_date_product', ['snapshot_date', 'product_id'], unique=False)
        batch_op.create_index('ix_inventory_snapshot_warehouse_id', ['warehouse_id'], unique=False)

    op.create_table('monthly_order_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_month', sa.String(length=7), nullable=False),
    sa.Column('arrival_month', sa.String(length=7), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('system_suggested_qty', sa.Integer(), nullable=False),
    sa.Column('user_modified_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'CONFIRMED')", name=op.f('ck_monthly_order_plan_monthly_order_plan_status_valid')),
    sa.CheckConstraint('system_suggested_qty >= 0', name=op.f('ck_monthly_order_plan_monthly_order_plan_suggested_non_negative')),
    sa.CheckConstraint('user_modified_qty >= 0', name=op.f('ck_monthly_order_plan_monthly_order_plan_modified_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_monthly_order_plan_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_order_plan')),
    sa.UniqueConstraint('target_month', 'product_id', name='uq_monthly_order_plan')
    )
    with op.batch_alter_table('monthly_order_plan', schema=None) as batch_op:
        batch_op.create_index('ix_monthly_order_plan_arrival_month', ['arrival_month'], unique=False)

    op.create_table('product_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('lineup_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_product_alias_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_alias')),
    sa.UniqueConstraint('source_name', name='uq_product_alias_source_name')
    )
    with op.batch_alter_table('product_alias', schema=None) as batch_op:
        batch_op.create_index('ix_product_alias_product_id', ['product_id'], unique=False)

    op.create_table('promotion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('source_product_name', sa.String(length=255), nullable=True),
    sa.Column('source_channel_name', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('slot_name', sa.String(length=255), nullable=True),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('list_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('reward_points', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('gift', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_marketing', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_promotion_promotion_date_order')),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_promotion_brand_id_brand')),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_promotion_channel_id_channel')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_promotion_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotion'))
    )
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.create_index('ix_promotion_brand_id', ['brand_id'], unique=False)
        batch_op.create_index('ix_promotion_period', ['start_date', 'end_date'], unique=False)
        batch_op.create_index('ix_promotion_product_id', ['product_id'], unique=False)

    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_month', sa.String(length=7), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_qty', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('order_qty > 0', name=op.f('ck_purchase_order_purchase_order_qty_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_purchase_order_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order'))
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index('ix_purchase_order_month_product', ['order_month', 'product_id'], unique=False)

    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=128), nullable=True),
    sa.Column('source_product_name', sa.String(length=255), nullable=False),
    sa.Column('source_channel_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('ship_date', sa.Date(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('iso_week BETWEEN 1 AND 53', name=op.f('ck_sales_order_sales_order_iso_week_range')),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], name=op.f('fk_sales_order_brand_id_brand')),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], name=op.f('fk_sales_order_channel_id_channel')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_sales_order_product_id_product')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_order'))
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index('ix_sales_order_brand_week', ['brand_id', 'iso_year', 'iso_week'], unique=False)
        batch_op.create_index('ix_sales_order_channel_id', ['channel_id'], unique=False)
        batch_op.create_index('ix_sales_order_product_id', ['product_id'], unique=False)
        batch_op.create_index('ix_sales_order_ship_date', ['ship_date'], unique=False)
        batch_op.create_index('ix_sales_order_source_product_name', ['source_product_name'], unique=False)
        batch_op.create_index('ix_sales_order_week', ['iso_year', 'iso_week'], unique=False)

    op.create_table('warehouse_product_moq',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('transfer_moq', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('transfer_moq >= 0', name=op.f('ck_warehouse_product_moq_warehouse_product_moq_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_warehouse_product_moq_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_warehouse_product_moq_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouse_product_moq')),
    sa.UniqueConstraint('warehouse_id', 'product_id', name='uq_warehouse_product_moq')
    )
    op.create_table('weekly_metric',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('beginning_qty', sa.Integer(), nullable=False),
    sa.Column('ending_qty', sa.Integer(), nullable=False),
    sa.Column('inbound_qty', sa.Integer(), nullable=False),
    sa.Column('outflow_qty', sa.Integer(), nullable=False),
    sa.Column('sales_qty', sa.Integer(), nullable=False),
    sa.Column('loss_qty', sa.Integer(), nullable=False),
    sa.Column('transfer_qty', sa.Integer(), nullable=False),
    sa.Column('sales_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("source IN ('DERIVED', 'IMPORTED')", name=op.f('ck_weekly_metric_weekly_metric_source_valid')),
    sa.CheckConstraint('beginning_qty >= 0', name=op.f('ck_weekly_metric_weekly_metric_beginning_non_negative')),
    sa.CheckConstraint('ending_qty >= 0', name=op.f('ck_weekly_metric_weekly_metric_ending_non_negative')),
    sa.CheckConstraint('iso_week BETWEEN 1 AND 53', name=op.f('ck_weekly_metric_weekly_metric_iso_week_range')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_weekly_metric_product_id_product')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], name=op.f('fk_weekly_metric_warehouse_id_warehouse')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_metric')),
    sa.UniqueConstraint('iso_year', 'iso_week', 'product_id', 'warehouse_id', name='uq_weekly_metric')
    )
    with op.batch_alter_table('weekly_metric', schema=None) as batch_op:
        batch_op.create_index('ix_weekly_metric_product_week', ['product_id', 'iso_year', 'iso_week'], unique=False)
        batch_op.create_index('ix_weekly_metric_warehouse_id', ['warehouse_id'], unique=False)
        batch_op.create_index('ix_weekly_metric_week', ['iso_year', 'iso_week'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_metric', schema=None) as batch_op:
        batch_op.drop_index('ix_weekly_metric_week')
        batch_op.drop_index('ix_weekly_metric_warehouse_id')
        batch_op.drop_index('ix_weekly_metric_product_week')

    op.drop_table('weekly_metric')
    op.drop_table('warehouse_product_moq')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_order_week')
        batch_op.drop_index('ix_sales_order_source_product_name')
        batch_op.drop_index('ix_sales_order_ship_date')
        batch_op.drop_index('ix_sales_order_product_id')
        batch_op.drop_index('ix_sales_order_channel_id')
        batch_op.drop_index('ix_sales_order_brand_week')

    op.drop_table('sales_order')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index('ix_purchase_order_month_product')

    op.drop_table('purchase_order')
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.drop_index('ix_promotion_product_id')
        batch_op.drop_index('ix_promotion_period')
        batch_op.drop_index('ix_promotion_brand_id')

    op.drop_table('promotion')
    with op.batch_alter_table('product_alias', schema=None) as batch_op:
        batch_op.drop_index('ix_product_alias_product_id')

    op.drop_table('product_alias')
    with op.batch_alter_table('monthly_order_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_monthly_order_plan_arrival_month')

    op.drop_table('monthly_order_plan')
    with op.batch_alter_table('inventory_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_inventory_snapshot_warehouse_id')
        batch_op.drop_index('ix_inventory_snapshot_date_product')

    op.drop_table('inventory_snapshot')
    with op.batch_alter_table('inbound', schema=None) as batch_op:
        batch_op.drop_index('ix_inbound_status')
        batch_op.drop_index('ix_inbound_product_id')
        batch_op.drop_index('ix_inbound_expiry_date')
        batch_op.drop_index('ix_inbound_eta')

    op.drop_table('inbound')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('ix_product_brand_id')

    op.drop_table('product')
    op.drop_table('logistics_cost')
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_index('ix_channel_warehouse_id')
        batch_op.drop_index('ix_channel_channel_group')

    op.drop_table('channel')
    op.drop_table('warehouse')
    op.drop_table('brand')
    # ### end Alembic commands ###
